spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.15.128:3306/mybatis
  redis:
    host: 192.168.15.128
mybatis:
  configuration:
    map-underscore-to-camel-case: false

